services:
  mysql:
    image: mariadb:10.8.3
    # Uncomment below when on Mac M1
    # platform: linux/arm64/v8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootD
    ports:
      - 3307:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080